### PR TITLE
Made a URL SHORTENER APP

### PR DESCRIPTION
**Pull request by JadhavSankalp7**
Made URL SHORTENER APP
https://github.com/JadhavSankalp7/A-URL_SHORTENER

## Describe the pull request

Please describe the changes proposed in this pull request.

## Contributors (in case of a commit with multiple authors)

Co-authors:

### CODE REVIEW

**Comment by JadhavSankalp7** [comment]
Made A URL Shortener App.

**Comment by cruxcode** [comment]
@darshitac11 are we taking submissions without looking at deployed app or the GIF?

**Comment by JadhavSankalp7** [comment]
Sir, I tried the deployment steps, I getting difficulty in the deployment. I referred the documentation but when I run the Run the command, yarn run server. It gives an error.

**Comment by darshitac11** [comment]
@JadhavSankalp7 - please share a video or a GIF to demonstrate how this app works.

**Comment by darshitac11** [comment]
@all-contributors please add @JadhavSankalp7 for code

**Pull request closed without merging**
