### PR TITLE
Carousel change

### PR DESCRIPTION
**Pull request by Jitulteron7**
Add a Carousel Component #170

### CODE REVIEW

**Comment by cruxcode** [comment]
@Jitulteron7 your Carousel component is blank. You need to write code for the Carousel component.

**Comment by Jitulteron7** [comment]
o sorry for this misunderstanding. 
If I upload an image or video where will it be saved I am trying to save it but the current version is not saving it

**Comment by darshitac11** [comment]
@all-contributors please add @Jitulteron7 for code

**Comment by darshitac11** [comment]
@all-contributors please add @Jitulteron7 for tests and code

**Pull request closed without merging**
