### PR TITLE
Added Alert into the react codebase

### PR DESCRIPTION
**Pull request by jonathanalvares9009**
I picked this issue as part of the assignment for frontend internship

### CODE REVIEW

**Comment by jonathanalvares9009** [comment]
@cruxcode, @darshitac11 could you please review the PR?

**Comment by cruxcode** [comment]
Hi Jonathan, can you make this alert component from scratch instead of using `@mui/material` library. Refer #216 for explanation.

**Comment by jonathanalvares9009** [comment]
Ok @cruxcode I'll do it without it.

**Comment by darshitac11** [comment]
@all-contributors please add @jonathanalvares9009 for tests and code

**Pull request closed without merging**
